### ISSUE TITLE
.gitignore and cached files in the repository

### ISSUE THREAD

**Issue by SterlingPeet** [arindam1993/MultiRobotEnvironment#1]
The main directory contains 4 .pyc files, despite the `.gitignore` file containing a rule to ignore those platform specific cache files.

I also noticed that the folders `images` and `reference_demos` are listed in the `.gitignore` file, but it looks like you actually don't want to exclude the folders themselves (which is the current configuration).  My best guess here is you want to keep the `images` folder and ignore the contents of the folder [and delete the jpgs currently in the repository under that folder], and not ignore the files in 'reference_demos`.

Personally, I suggest looking at github's [Python .gitignore file](https://github.com/github/gitignore/blob/master/Python.gitignore) and using it directly with a specific addition for the folders at the top.

I can package this up into a pull request if you would like, provided you give some feedback on how the folders are supposed to behave.

Thanks,

@SterlingPeet

**Comment by arindam1993** [comment]
I have been meaning to clean up the repository for a while now, this mess started off because I didn't configure the Git client within Eclipse properly, and I kept putting off fixing it.
Both the folders are to be excluded as well as all the .pyc, .pydevproject and .project files. I was just going to create a new clean branch and reset master from it. However, if you have already done this I'd be glad to accept the pull request.

**Comment by SterlingPeet** [comment]
Makes sense, I can set up the pull request shortly.   I suspected you might want to keep the example file in the repository, deleting it (or not) is easy.

**Comment by arindam1993** [comment]
I already cleaned up the repository. Thanks a lot for pointing this out though, you finally gave me the motivation to do this!

**Comment by SterlingPeet** [comment]
Awesome, thanks!

**Comment by SterlingPeet** [comment]
Oops, I just noticed you seem to have killed your .gitignore file

**Comment by arindam1993** [comment]
Oh Yea, Thanks, merged you pull request!
